# Generated by Django 4.1.7 on 2023-03-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tag", "0004_tag_author"),
        ("post", "0002_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="tag.tag"
            ),
        ),
    ]
